### ISSUE TITLE
english version ?

### ISSUE THREAD

**Issue by amarCosmospace** [HaujetZhao/QuickCut#7]
Hi, 
First of all, nice work you've done.
Planning any english/translated version ?

I can participate in translation.

**Comment by HaujetZhao** [comment]
After adding one more function, I'll prepare the translation and notify you. Thanks so much!

**Comment by shniubobo** [comment]
> After adding one more function, I'll prepare the translation and notify you. Thanks so much!

我也愿意参加翻译，如果需要的话请到时也通知我。

I'm willing to participate in the translation work too. Please notify me if I can be of any help.

**Comment by HaujetZhao** [comment]
@shniubobo @amarCosmospace 已经写好翻译指南，请查看 readme

**Comment by shniubobo** [comment]
> @shniubobo @amarCosmospace 已经写好翻译指南，请查看 readme

请问是否可以把翻译分配给我们中的一个人，或给每个人分配不同的部分？这样可以防止撞车。另外我建议在翻译指南中要求在翻译前先开个issue，并要求每个翻译者翻译前先查一下open issue看看是不是有人在做了，这样也可以防止撞车。另外[这个](https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users)可能会对你有用。

Could you please assign the translation to one of us, or assign different parts of it to each of us, so that our work won't duplicate? Also I suggest translators be asked to open an issue before they start working, and be asked to check open issues to make sure no one else is working on the translation, which will also prevent duplicate translation. Also [this](https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users) may be of help.
